### ISSUE TITLE
Request: change order of icons in markers tab

### ISSUE THREAD

**Issue by Dschaykib** [mnist91/origin#2]
I would suggest changing the order of the icon in the marker tab.
If something in a line is changed (info) if should be the dominating icon. At the moment a not changes part has a higher prior.

![Screenshot 2021-06-10 at 10 38 26](https://user-images.githubusercontent.com/26231434/121493303-fde92a00-c9d7-11eb-9adb-5b8695b145fb.png)

**Comment by mnist91** [comment]
Thank you for your feedback. The reasoning behind this design decision has been to be as conservative as possible about inserting `pkg::`. On the flip side, "false negatives" (missed insertions) are more likely and the user should pay more attention to those. Since both insertions, as well as missed insertions, are code-breaking, the priority between both is arbitrary in my opinion. I might be in the wrong however and will keep this issue open in case it is shared by the broad user base. 

I could also include this as an option/argument to be a user input.

**Comment by mnist91** [comment]
Implemented in 1.0.0
