### ISSUE TITLE
check_pkg_origin gives error on Latex strings

### ISSUE THREAD

**Issue by friendly** [mnist91/origin#8]
In the `R/` folder for a book pkg, I have have occasional strings containing LaTeX expressions, like

```
eqn <- "
\begin{equation*}
\overset{\mathbf{SSP}_T}
  {\begin{pmatrix} 
   35.4 & -59.2 \\ 
  -59.2 & 975.9 \\ 
  \end{pmatrix}}
"
```

Running `check_pkg_origin()` gives this error:

```
> pkg_usage <- check_pkg_usage()
Error: '\o' is an unrecognized escape in character string (C:/R/Projects/Vis-MLM-book/R/dogfood-ex.R:77:2)
```

These obviously should be ignored. If I try to exclude the entire `R/` folder, I get a different error:

```
> pkg_usage <- check_pkg_usage(exclude_files="R/*")
Error in check_pkg_usage(exclude_files = "R/*") : 
  File to exclude not in given path
R/*
```

**Comment by mnist91** [comment]
Thanks for your input.

Regarding the first topic: the error is thrown by `base::parse()` which is called within origin. Since this code itself throws an error, I am unsure whether origin could or should handle this since it relies on **parsable** code.

For the latter, I refer to the documentation:
> `exclude_files` - a character vector of file paths that should be excluded from being checked. Helpful if all but a few files should be considered by origin.

So you cannot just use a pattern but need to wrap it around `list.files`

```
to_exclude <- list.files(path = "R/", full.names = TRUE)
check_pkg_usage(exclude_files = to_exclude)
```
